ERROR:cfscanner.main:Could not read subnets
Traceback (most recent call last):
  File "/home/smz/Documents/GitHub/CFScanner/python/cfscanner/main.py", line 122, in main
    cidr_list = read_cidrs(args.subnets)
  File "/home/smz/Documents/GitHub/CFScanner/python/cfscanner/subnets/cidr.py", line 155, in read_cidrs
    raise SubnetsReadError(
cfscanner.utils.exceptions.SubnetsReadError: "/home/smz/Downloads/custom_subnets.txt" is neither a valid url nor a file path.
